apiVersion: v1
kind: Service
metadata:
  name: waiter-headless
  namespace: waiter
spec:
  clusterIP: None
  selector:
    app: waiter-worker
  ports:
  - name: epmd
    port: 4369
    targetPort: 4369
