apiVersion: v1
kind: Service
metadata:
  name: ingress-waiter
  namespace: waiter
spec:
  type: LoadBalancer
  selector:
    app: waiter-worker
  ports:
  - name: http
    port: 80
    targetPort: 4000
