apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: waiter-controller
  namespace: waiter
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses", "ingressclasses"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list", "watch"]
