apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: waiter-controller
  namespace: waiter
subjects:
- kind: ServiceAccount
  name: waiter-controller
roleRef:
  kind: Role
  name: waiter-controller
  apiGroup: rbac.authorization.k8s.io
